#define SUNNY_NO_ERROR								0
#define SUNNY_FILE_NOT_FOUND_ERROR					1
#define SUNNY_PARSE_TYPES_ERROR						2
#define SUNNY_MEMORY_LEAK_ERROR						3

#define SUNNY_BUFFER_CREATE_ERROR					10

#define SUNNY_DATAPOOL_EMPTY_ERROR					20
#define SUNNY_DATAPOOL_FORMAT_ERROR					21
#define SUNNY_DATAPOOL_ITEM_NAME_ERROR				22
#define SUNNY_DATAPOOL_UNKNOW_DATA_TYPE				23

#define SUNNY_NETWORK_IP_ERROR						31
#define SUNNY_NETWORK_REGISTER_PROTOCOL_ERROR		32


#define SUNNY_UNKNOWN_ERROR							999
